"""Bug status report builder (from synced OpenProject data).

Flow: pick a project → select bugs → render the FlyNava email template
(OP ID · Bug Type · Bug Name · Assignee · Accountable) → send via SMTP, or
return a preview when SMTP isn't configured. Bug Type / Bug Name are parsed
from OpenProject's `PREFIX | subject` convention (e.g. "REPLICA | Rules ...").
"""
from __future__ import annotations

import html as html_lib
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from pymongo.database import Database

from ..config import settings

_BUG_Q = {"wp_type": {"$regex": "bug", "$options": "i"}}


def _split_subject(title: str, wp_type: str | None) -> tuple[str, str]:
    """"REPLICA | Rules query" -> ("REPLICA", "Rules query")."""
    if title and "|" in title:
        prefix, rest = title.split("|", 1)
        return prefix.strip(), rest.strip()
    return (wp_type or "Bug"), (title or "")


def _row(db: Database, t: dict) -> dict:
    bug_type, bug_name = _split_subject(t.get("title", ""), t.get("wp_type"))
    return {
        "op_id": t.get("source_id"),
        "bug_type": bug_type,
        "bug_name": bug_name,
        "title": t.get("title"),
        "status": t.get("status"),
        "priority": t.get("priority"),
        "assignee": t.get("assignee") or "—",
        "accountable": t.get("author") or "—",
        "url": f"{settings.openproject_base_url}/work_packages/{t.get('source_id')}",
    }


def list_projects(db: Database) -> list[dict]:
    """OpenProject projects with a bug count (only ones that have bugs)."""
    out = []
    for p in db.projects.find({"source_system": "openproject"}):
        n = db.tasks.count_documents({**_BUG_Q, "project_source_id": p["source_id"]})
        if n:
            out.append({"source_id": p["source_id"], "name": p.get("name"), "bug_count": n})
    return sorted(out, key=lambda x: -x["bug_count"])


def list_bugs(db: Database, project: str, status: str | None = None,
              priority: str | None = None, limit: int = 500) -> list[dict]:
    q: dict = {**_BUG_Q, "project_source_id": project}
    if status:
        q["status"] = status
    if priority:
        q["priority"] = priority
    return [_row(db, t) for t in db.tasks.find(q).limit(limit)]


def bugs_by_ids(db: Database, ids: list[str]) -> list[dict]:
    rows = [_row(db, t) for t in db.tasks.find(
        {"source_system": "openproject", "source_id": {"$in": ids}})]
    order = {i: n for n, i in enumerate(ids)}
    return sorted(rows, key=lambda r: order.get(r["op_id"], 1e9))


def render_html(title: str, intro: str, rows: list[dict]) -> str:
    def td(v: str) -> str:
        return f'<td style="border:1px solid #d9d9d9;padding:6px 10px;font-size:13px;">{html_lib.escape(str(v))}</td>'

    head = "".join(
        f'<th style="border:1px solid #d9d9d9;padding:6px 10px;background:#157f52;'
        f'color:#fff;font-size:13px;text-align:left;">{h}</th>'
        for h in ["OP ID", "Bug Type", "Bug Name", "Assignee", "Accountable"]
    )
    body = "".join(
        "<tr>"
        f'<td style="border:1px solid #d9d9d9;padding:6px 10px;font-size:13px;">'
        f'<a href="{html_lib.escape(r["url"])}">{html_lib.escape(str(r["op_id"]))}</a></td>'
        + td(r["bug_type"]) + td(r["bug_name"]) + td(r["assignee"]) + td(r["accountable"])
        + "</tr>"
        for r in rows
    )
    intro_html = f"<p>{html_lib.escape(intro)}</p>" if intro else ""
    return (
        f'<div style="font-family:Segoe UI,Arial,sans-serif;color:#1f1f1f;">'
        f"<p>Hi Team,</p>{intro_html}"
        f'<table style="border-collapse:collapse;margin-top:8px;">'
        f"<thead><tr>{head}</tr></thead><tbody>{body}</tbody></table>"
        f'<p style="margin-top:12px;color:#6b7280;font-size:12px;">'
        f"{len(rows)} item(s) · generated by IO — FlyNava Technologies</p></div>"
    )


def send_email(subject: str, html: str, recipients: list[str]) -> dict:
    if not (settings.smtp_host and settings.smtp_user and recipients):
        return {"status": "preview",
                "detail": "SMTP not configured — showing preview only."}
    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = settings.smtp_from or settings.smtp_user
    msg["To"] = ", ".join(recipients)
    msg.attach(MIMEText(html, "html"))
    with smtplib.SMTP(settings.smtp_host, settings.smtp_port, timeout=20) as s:
        if settings.smtp_use_tls:
            s.starttls()
        s.login(settings.smtp_user, settings.smtp_password)
        s.sendmail(msg["From"], recipients, msg.as_string())
    return {"status": "sent", "detail": f"Sent to {len(recipients)} recipient(s)."}
